### ISSUE TITLE
Why change the status bar color after shacked?

### ISSUE THREAD

**Issue by a11enwong** [Instabug/Instabug-iOS#45] opened 2015-12-27 19:57 UTC
Please check out the screen shot, any way to configuration it?
![3 pic_hd](https://cloud.githubusercontent.com/assets/2629148/12011776/05a8e124-ad17-11e5-9dc2-85675de5c0a0.jpg)

**Comment by msoliman** [comment] 2015-12-27 20:34
@a11enwong it's supposed to follow the same UIStatusBarStyle. What does your view hierarchy looks like? The status bar style is inferred from the VC at the end of the presentation chain of the root VC of the keyWindow. Do you have something different?

**Comment by msoliman** [comment] 2016-02-04 07:26
@a11enwong This should be fixed in the latest release v5.0.2.
Check it out and please re-open this if you're still able to reproduce.

**Closed by msoliman** 2016-02-04 07:26 UTC
