### ISSUE TITLE
Instabug crash during AWS S3 outage

### ISSUE THREAD

**Issue by bdolman** [Instabug/Instabug-iOS#132] opened 2017-03-01 21:52 UTC
Yesterday we had 100 Instabug-caused crashes during the AWS outage. They stopped once AWS came back up. Stack trace is included below. Perhaps your code isn't properly handling network failures?

```
Fatal Exception: NSInvalidArgumentException -[NSTaggedPointerString objectForKeyedSubscript:]: unrecognized selector sent to instance 0xa737365636375737
0  CoreFoundation                 0x18ce711b8 __exceptionPreprocess
1  libobjc.A.dylib                0x18b8a855c objc_exception_throw
2  CoreFoundation                 0x18ce78268 __methodDescriptionForSelector
3  CoreFoundation                 0x18ce75270 ___forwarding___
4  CoreFoundation                 0x18cd6e80c _CF_forwarding_prep_0
5  Instabug                       0x101220b3c +[IBGSurvey surveysFromResponseArray:] (IBGSurvey.m:34)
6  Instabug                       0x1012472b4 -[IBGSurveysRequest dataServerExecutionDone:statusCode:error:response:] (IBGSurveysRequest.m:73)
7  Instabug                       0x1012023f8 __75+[IBGServerDataRequest executeWithURL:HTTPMethod:payload:headers:delegate:]_block_invoke_2 (IBGServerDataRequest.m:150)
8  Instabug                       0x101202034 -[IBGServerDataRequest prepareResponseWithData:error:rawResponse:completionHandler:] (IBGServerDataRequest.m:119)
9  Instabug                       0x10120234c __75+[IBGServerDataRequest executeWithURL:HTTPMethod:payload:headers:delegate:]_block_invoke (IBGServerDataRequest.m:146)
10 CFNetwork                      0x18d5502bc __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2
11 Foundation                     0x18d95ffb0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
12 Foundation                     0x18d8a4aa8 -[NSBlockOperation main]
13 Foundation                     0x18d8950a4 -[__NSOperationInternal _start:]
14 Foundation                     0x18d96235c __NSOQSchedule_f
15 libdispatch.dylib              0x18bcfa1bc _dispatch_client_callout
16 libdispatch.dylib              0x18bd083dc _dispatch_queue_serial_drain
17 libdispatch.dylib              0x18bcfd9a4 _dispatch_queue_invoke
18 libdispatch.dylib              0x18bd0a34c _dispatch_root_queue_drain
19 libdispatch.dylib              0x18bd0a0ac _dispatch_worker_thread3
20 libsystem_pthread.dylib        0x18bf032a0 _pthread_wqthread
21 libsystem_pthread.dylib        0x18bf02d8c start_wqthread
```

**Comment by Figo0o** [comment] 2017-03-01 22:22
Apologizes @bdolman for that. This will be fixed in the upcoming release to prevent this crashes happens in future. Thanks for reporting that out.

**Comment by keith** [comment] 2017-03-02 00:27
Duplicate of https://github.com/Instabug/Instabug-iOS/issues/131

@Figo0o FWIW I just captured this crash in the debugger as well. AFAIK AWS is back up and running, so there might be another cause here. Should we downgrade the SDK to a previous version to avoid this crash in the meantime?

**Comment by Figo0o** [comment] 2017-03-02 06:59
@keith, Can you provide me with the application's token over support@instabug.com? I'm gonna follow up with you.

**Comment by HeshamMegid** [comment] 2017-03-02 16:20
@bdolman @keith please update to v7.0.4 of the SDK. During the next AWS outage (😬) the SDK would not crash.

**Closed** 2017-03-02 16:20 UTC
