### ISSUE TITLE
Status bar white when it should be black

### ISSUE THREAD

**Issue by timroesner** [Instabug/Instabug-iOS#190] opened 2017-09-15 23:44 UTC
### Steps to reproduce the problem

1. Set View Controller based status bar in plist to NO
2. Set status bar to light content in viewDidLoad
3. Invoke Instabug

### Expected behavior

4. Status bar should be black when reporting a bug

### Actual behavior

4. Status bar is white and not legible when reporting a bug

### Instabug integration code "Don't put your token publicly"

Through CocoaPods as describe in readme

### SDK version

Latest available 

### iOS Version

iOS 11

### Device

iPhone 6s

**Comment by NadineMansour** [comment] 2017-09-16 08:22
@timroesner Thank you so much for the details. 
We will look into it right away. 
I will keep you updated.

**Comment by NadineMansour** [comment] 2017-09-16 15:36
@timroesner Here is a [custom build](https://www.dropbox.com/s/8psuzjofl9mchlr/Instabug.zip?dl=0) where the issue is fixed. 
Please give it a try and let me know if everything is as expected or not.

**Comment by timroesner** [comment] 2017-09-16 22:02
Thanks @NadineMansour that fixed it. Any chance this will be implemented in the master branch, or will I have to use this custom framework going forward?

**Comment by NadineMansour** [comment] 2017-09-16 22:15
@timroesner It is my pleasure. 
We will release the fix soon. I will make sure to notify you once it is out.

**Comment by Kmohamed** [comment] 2017-10-15 06:30
@timroesner the fix is released in SDK version 7.3.9.

**Closed by Kmohamed** 2017-10-15 06:30 UTC
