### ISSUE TITLE
`Copy Pods Resources` Build Phase Failed in Enterprise Build

### ISSUE THREAD

**Issue by rudolfchengsc** [Instabug/Instabug-iOS#94] opened 2016-11-02 16:57 UTC
When building an enterprise build with `fastlane`, `Copy Pods Resources` build phase fails when I use the latest version of Instabug, while v5.3 succeeds.  Am I doing something wrong or it warrants some investigation?

**Comment by Figo0o** [comment] 2016-11-05 21:01
Hey @rudolfchengsc, Let me check this for you and get back to you.

**Comment by rudolfchengsc** [comment] 2016-11-06 16:12
Thx!  FYI, I'm using cocoapods v3.8.2 and ruby 2.0.0.  Don't ask... LOL

**Comment by HeshamMegid** [comment] 2016-11-10 11:14
Hi @rudolfchengsc. Unfortunately, I have been unable to reproduce this issue.

Would you please make sure you are on the latest version of both Cocoapods and fastlane and let me know if this still fails? If it does, please share more info about your fastlane setup and which lanes you use.

**Comment by walsht** [comment] 2016-11-26 14:52
I am having the same issue.  I am using cocoapods-1.1.1 and just running cocopods update, I get Installing Instabug (6.1)
I get this exception when building to Release scheme, Debug works fine. 
`Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_Instabug", referenced from:
      objc-class-ref in WiTSettingsViewController.o
      objc-class-ref in WiTCommonAppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by walsht** [comment] 2016-11-26 14:58
This resolved my issue.
https://github.com/Instabug/Instabug-iOS/issues/14

**Comment by HeshamMegid** [comment] 2016-11-28 11:56
@walsht, the issue you're having has been fixed in 6.1.1. Please update and let me know if you're still experiencing the same problem.

**Closed** 2016-12-14 06:37 UTC
