### ISSUE TITLE
Xamarin.iOS: Could not decompress the native framework 'Instabug.framework'

### ISSUE THREAD

**Issue by moreirawebmaster** [Instabug/Instabug-iOS#348] opened 2019-12-02 12:35 UTC
Hello Guys!

When last version update, my app broken.

![Screen Shot 2019-12-02 at 09 32 29](https://user-images.githubusercontent.com/1142139/69959958-090bf180-14e7-11ea-9105-6e5f2e4e11c8.png)

```
Severity | Code | Description | Project | File | Line | Suppression State | Suppression State
-- | -- | -- | -- | -- | -- | -- | --
Error |   | Could not decompress the native framework 'Instabug.framework' from '/Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework.zip'. Please review the build log for more information from the native 'unzip' command. | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGReportCategoriesVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGReportCategoriesVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGReportCategoriesVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGPromptVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGPromptVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  
Error |   | /Users/ventron.tmoreira/Library/Caches/Xamarin/mtbs/builds/Vitreo.App.iOS/e4da14bc474c03a6d48c958881a30dc6/obj/iPhoneSimulator/Debug/mtouch-cache/Instabug.framework/InstabugResources.bundle/IBGPromptVC-iPhone.nib exists but is not directory | Vitreo.App.iOS |   |   |   |  

```

### SDK Version
8.7.2
### iOS Version
13

**Comment by AliAbdelfattah** [comment] 2019-12-02 13:50
@moreirawebmaster thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment] 2019-12-03 10:55
Hi @moreirawebmaster, could you send us the VS tools versions details, please? 

From Visual Studio > About Visual Studio > Click on "Show Details"

**Comment by pschroeder89** [comment] 2020-01-06 21:48
Any news on this, @AliAbdelfattah ? I'm seeing this behavior as well

**Comment by AliAbdelfattah** [comment] 2020-01-07 11:34
Hi @pschroeder89, are you using Instabug-Xamarin or the Instabug-iOS SDK?

**Comment by pschroeder89** [comment] 2020-01-07 16:14
@AliAbdelfattah We are using Instabug-iOS. I updated fastlane / ruby on that machine and now we can unzip the compressed file just fine.

**Comment by AliAbdelfattah** [comment] 2020-03-29 16:18
Closing this as we're unable to reproduce it.

**Closed by AliAbdelfattah** 2020-03-29 16:18 UTC
