### ISSUE TITLE
Couldn't update Instabug SDK to 9.1.1 on Xcode 11.4.1

### ISSUE THREAD

**Issue by nicopuri** [Instabug/Instabug-iOS#365] opened 2020-04-19 02:57 UTC
### Steps to Reproduce the Problem

1. Install Xcode 11.4.1
2. Update Instabug SDK
```
binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json" == 9.1.1
```
3. Execute `carthage update Instabug --platform iOS`

### Expected Behavior

Can run the app on Xcode 11.4.1

### Actual Behavior

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/362966/79678277-fbbe7d80-81cf-11ea-9efc-3f9d5ac7c0b1.png">

```
*** Downloading binary-only framework Instabug at "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json"
*** xcodebuild output can be found in /var/folders/2n/6c_26qqj63bb93typb43vg8c0000gn/T/carthage-xcodebuild.Ok6Vfw.log
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51).
```

### SDK Version

9.1.1

**Comment by Kmohamed** [comment] 2020-04-19 03:19
Duplicate of #364
It’s a Carthage issue but their is a workaround.

**Closed** 2020-04-19 03:19 UTC
