### ISSUE TITLE
Console network spam

### ISSUE THREAD

**Issue by RiverbayChris** [Instabug/Instabug-iOS#272] opened 2018-07-12 11:55 UTC
### Steps to Reproduce the Problem
Run app with Instabug on hardware (I'm testing on iPod Touch).

### Expected Behavior
No spam

### Actual Behavior
I get "Could not successfully update network info during initialization" spammed to the Xcode console

### SDK Version
8.0.4

### iOS Version
11.4

### Device Type
iPod Touch (latest gen)

**Comment by Kmohamed** [comment] 2018-07-12 12:06
@RiverbayChris so If you remove Instabug the console log disappear ?

**Comment by Kmohamed** [comment] 2018-07-12 13:05
this was because a different reason because we were trying to fetch connection type of a simulator and it's fixed let me check it

**Comment by Kmohamed** [comment] 2018-07-12 13:54
I just tried it and did not print anything in the console could you send me your Instabug code (The APIs that you use)?

**Comment by RiverbayChris** [comment] 2018-07-13 15:35
I have only a single line of Instabug code in my AppDelegate didFinishLaunching method:

Instabug.start(withToken: "xxx", invocationEvents: .shake)

**Comment by RiverbayChris** [comment] 2018-07-13 15:52
For what it's worth, this message does not occur when I run in simulator.

**Comment by Kmohamed** [comment] 2018-07-14 07:43
I will try to reproduce it and get back to you.

**Comment by Kmohamed** [comment] 2018-07-15 08:58
@RiverbayChris are you using Facebook SDK is so could you try to remove it from appDelegate ?

**Comment by Kmohamed** [comment] 2018-07-16 01:40
@RiverbayChris could you give this custom build a try it should fix it.
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'simcard-check'

**Comment by RiverbayChris** [comment] 2018-07-16 12:01
I’m using Carthage, but can’t get that “simcard-check' branch to build.  

*** Checking out Instabug-iOS at "77601df541308b7cf55f739580861a79d6087b88"
*** xcodebuild output can be found in /var/folders/sg/y_rv5vz17pz652mx032cs0k40000gn/T/carthage-xcodebuild.hEdo3Z.log
*** Skipped building Instabug-iOS due to the error:
Dependency "Instabug-iOS" has no shared framework schemes

**Comment by Kmohamed** [comment] 2018-07-16 12:18
@RiverbayChris could you try to install it manual ?

**Comment by ramiimagdi** [comment] 2018-07-23 12:32
@RiverbayChris 
Were you able to manually install it? We'll be looking forward to hearing back from you.

**Comment by ramiimagdi** [comment] 2018-07-26 19:17
@RiverbayChris Allow me to close this ticket here, and please feel free to get back to us if you have any questions at all. Have a great day.

**Closed by ramiimagdi** 2018-07-26 19:17 UTC
