### ISSUE TITLE
[Bug], [Function request] Color theme does not change when overrideUserInterfaceStyle changes

### ISSUE THREAD

**Issue by lisindima** [Instabug/Instabug-iOS#356] opened 2020-02-25 04:11 UTC
### Steps to Reproduce the Problem
Try setting in SceneDelegate overrideUserInterfaceStyle in .dark, the Instabug window will continue to inherit the color of the system
### Expected Behavior
Instabug window inherit color from overrideUserInterfaceStyle
### Actual Behavior
Instabug window will continue to inherit the color of the system
### SDK Version
v9.0.10
### iOS Version
13.4
### Device Model
iPhone 11 Pro

**Comment by Kmohamed** [comment] 2020-02-25 04:13
Hello @lisindima 
Why do you think we should not follow the system theme? Because this was by design

**Comment by lisindima** [comment] 2020-02-25 04:20
Hi @Kmohamed, I have an application built on SwiftUI, it has a toggle that sets a forced dark theme in the application through overrideUserInterfaceStyle (it has three values, it is light, dark and inherit the color of the system) when I switch this toggle my application is completely displayed in dark colors, except instabug screen. I just suggest considering adding this theme management mode to instabug.

**Comment by Kmohamed** [comment] 2020-02-25 09:37
@lisindima I interested to know what will be the case if you show a native alert like permission or something else. I am trying to validate the use-case to forward it to our product team.

**Comment by lisindima** [comment] 2020-02-25 10:08
All system elements (alert, actionSheet) also inherit overrideUserInterfaceStyle without problems. Even the status bar changes color, adjusting to a dark theme.

**Comment by Kmohamed** [comment] 2020-02-25 17:14
@lisindima Perfect let me forward this to our product team and get back to you.

**Comment by Kmohamed** [comment] 2020-02-26 09:47
@lisindima What about using our API in this case 

>  I have an application built on SwiftUI, it has a toggle that sets a forced dark theme in the application

So I the user enables dark mode you can use this API. `Instabug.setColorTheme(.dark)` and If he disables the dark mode you can use this `Instabug.setColorTheme(.light)`

What do you think?

**Comment by lisindima** [comment] 2020-02-26 11:06
I tried to use this api, it works, but not quite as it should in my situation. There is no problem when the toggle is active, the application forcibly goes into dark mode, and the api is installed in Instabug.setColorTheme (.dark). But problems begin when the toggle is inactive, and the system controls the color of the application. When deactivating toggle, we install api in Instabug.setColorTheme (.light). But when the system changes the theme color to dark, Instabug view will remain light because it remembers it Instabug.setColorTheme (.light).... The solution may be this: The logic of switching to dark remains unchanged, we pass Instabug.setColorTheme (. dark), and when the toggle is turned off, we transfer something similar to Instabug.setColorTheme (.reset) so that the Instabig view starts to inherit the system theme again, as if we didn’t forcibly tell it Instabug.setColorTheme. I hope you got what I meant)

**Comment by lisindima** [comment] 2020-03-04 05:02
Good afternoon, is there any news?)

**Comment by Kmohamed** [comment] 2020-03-04 07:12
Good morning, It's already inside our backlog not sure when it will be released. but if it's a blocker for you we can send you a custom build.

**Comment by lisindima** [comment] 2020-03-04 08:59
No, this is not necessary, thanks)

**Comment by Kmohamed** [comment] 2020-03-04 09:06
I really appreciate your collaboration 🙏

**Closed** 2021-06-22 16:19 UTC
Labels: Feature Request
