### ISSUE TITLE
Crash [NSURLRequest(Additions) ibg_cURLCommandWithBody:]

### ISSUE THREAD

**Issue by McFlyssss** [Instabug/Instabug-iOS#162] opened 2017-06-01 14:49 UTC
Hi guys,

One of our testers is experiencing an issue in which the app crashes every single time it opens.
Last time he reported a bug the screenshot was never uploaded (It does not appear in the dashboard) and since then the issue keeps happening.

```
#3. Crashed: NSOperationQueue 0x17003ee20 :: NSOperation 0x174248fd0 (QOS: DEFAULT)
0  CoreFoundation                 0x188461540 __CFStringChangeSizeMultiple + 2316
1  CoreFoundation                 0x1883b7c74 CFStringFindAndReplace + 1016
2  Instabug                       0x1013cd428 -[NSURLRequest(Additions) ibg_cURLCommandWithBody:] (NSURLRequest+Additions.m:40)
3  Instabug                       0x1013cdae0 -[NSURLRequest(Additions) ibg_InstabugcURLCommand] (NSURLRequest+Additions.m:75)
4  Instabug                       0x1014099d0 +[IBGServerDataRequest executeWithURL:HTTPMethod:payload:headers:delegate:] (IBGServerDataRequest.m:144)
5  Instabug                       0x1014098c0 +[IBGServerDataRequest executeWithURL:HTTPMethod:payload:delegate:] (IBGServerDataRequest.m:125)
6  Instabug                       0x1013d38c8 -[IBGLogRequest executeNow] (IBGLogRequest.m:37)
7  Instabug                       0x10145a034 -[IBGServerManager refresh] (IBGServerManager.m:95)
8  Instabug                       0x10145a1bc -[IBGServerManager handleRequest:] (IBGServerManager.m:110)
9  Instabug                       0x1013d30c8 -[IBGLocalAttachment reportAttachmentRequestDone:isSuccess:error:] (IBGLocalAttachment.m:108)
10 Instabug                       0x101465680 -[IBGReportAttachmentRequest fileServerExecutionDone:statusCode:error:response:] (IBGReportAttachmentRequest.m:67)
11 Instabug                       0x1013a57a0 __66+[IBGServerFileRequest executeWithURL:filePath:fileInfo:delegate:]_block_invoke_2 (IBGServerFileRequest.m:125)
12 Instabug                       0x1013a5474 -[IBGServerFileRequest prepareResponseWithData:error:rawResponse:completionHandler:] (IBGServerFileRequest.m:111)
13 Instabug                       0x1013a56f4 __66+[IBGServerFileRequest executeWithURL:filePath:fileInfo:delegate:]_block_invoke (IBGServerFileRequest.m:121)
14 CFNetwork                      0x188b7f780 __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2 + 180
15 Foundation                     0x188f65814 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
16 Foundation                     0x188eaa770 -[NSBlockOperation main] + 96
17 Foundation                     0x188e9ab28 -[__NSOperationInternal _start:] + 612
18 Foundation                     0x188f67bb0 __NSOQSchedule_f + 228
19 libdispatch.dylib              0x18734e9a0 _dispatch_client_callout + 16
20 libdispatch.dylib              0x18735cad4 _dispatch_queue_serial_drain + 928
21 libdispatch.dylib              0x1873522cc _dispatch_queue_invoke + 884
22 libdispatch.dylib              0x18735ea50 _dispatch_root_queue_drain + 540
23 libdispatch.dylib              0x18735e7d0 _dispatch_worker_thread3 + 124
24 libsystem_pthread.dylib        0x187557100 _pthread_wqthread + 1096
25 libsystem_pthread.dylib        0x187556cac start_wqthread + 4
```

Re-installing the app fixed the problem.

Cheers,

Albert

**Comment by Figo0o** [comment] 2017-06-01 21:24
Hello Albert, 

Can you provide us with Instabug version used and what is the exception ? .. Can you reproduce it again ?

**Comment by McFlyssss** [comment] 2017-06-02 10:03
Hello @Figo0o ,

Sorry, I forgot to include the basic information:
- Instabug version is 7.2.6
- EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000001affff40

I can not reproduce it again. We had to delete the app and install it again. Working fine since then.

Cheers,

Albert

**Comment by Figo0o** [comment] 2017-07-02 08:42
Since we can't reproduce this issue and till now it didn't happen again, I'm gonna close this until any updates shows up.

**Closed by Figo0o** 2017-07-02 08:42 UTC
