### ISSUE TITLE
Options alert not shown after invocation - 'clicking on floatingButton' or 'Shake' 

### ISSUE THREAD

**Issue by pk123hk2003** [Instabug/Instabug-iOS#302] opened 2018-12-04 16:50 UTC
### Steps to Reproduce the Problem

Tap on Floating action button. 

### Expected Behavior

Expect to see pop up options 

### Actual Behavior

Floating action button disappear after click and no pop up was shown

### Instabug integration code

          if (self.isRunningLive()) {
            Instabug.start(withToken: "App-Token", invocationEvents: [.shake, .floatingButton])
          } else {
            Instabug.start(withToken: "App-Token", invocationEvents: [.shake, .floatingButton])
          }

       BugReporting.promptOptions = [.bug, .feedback]

### SDK Version

Verion: 8.0.17

### iOS Version

iOS 12.1 

### Device Model

iPhone 7 Plus

**Comment by Kmohamed** [comment] 2018-12-04 17:31
This usually happens if you Enter an invalide token. could you double check the token ?
If the token is correct could you contact the customer happiness in order to send the token.

**Comment by pk123hk2003** [comment] 2018-12-04 17:48
Hi @Kmohamed Thanks for getting back to me. I can confirm the token was correct, I tested it further and I was able to get the pop up (if I am lucky) but most the time nothing happens after invocation.

**Comment by Kmohamed** [comment] 2018-12-04 17:54
Could you please contact customer happiness and I will flow up with you

**Comment by Kmohamed** [comment] 2018-12-06 14:13
@pk123hk2003 I think the issue is fixed now. so I will close it feel free to open it again anytime if you face it.

**Closed by Kmohamed** 2018-12-06 14:13 UTC
