### ISSUE TITLE
Crash with 7.4

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#223] opened 2018-01-10 14:31 UTC
We're seeing this crash with SDK version 7.4. We've upgraded locally, but aren't sure yet whether or not this is fixed with newer versions.

```
NSInvalidArgumentException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          __CFThrowFormattedException
3  CoreFoundation          -[__NSPlaceholderArray initWithObjects:count:]
4  CoreFoundation          +[NSArray arrayWithObjects:count:]
5  CoreFoundation          -[NSDictionary allValues]
6  InstabugCore            derive_key
7  InstabugCore            derive_key
8  InstabugCore            derive_key
9  Foundation              ___NSOQSchedule_f
10 libdispatch.dylib       __dispatch_client_callout
11 libdispatch.dylib       __dispatch_continuation_pop$VARIANT$mp
12 libdispatch.dylib       __dispatch_async_redirect_invoke$VARIANT$mp
13 libdispatch.dylib       __dispatch_root_queue_drain
14 libdispatch.dylib       __dispatch_worker_thread3
15 libsystem_pthread.dylib __pthread_wqthread
16 libsystem_pthread.dylib _start_wqthread
```

**Comment by Kmohamed** [comment] 2018-01-10 14:33
@keith  could you provide complete stack-trace ?

**Comment by keith** [comment] 2018-01-10 14:35
Unfortunately our crash reporting provider doesn't store the original report. There isn't much else from the other threads related to instabug though, although I found this one on a different thread:

```
0	libsystem_kernel.dylib	_write
1	Foundation	__NSWriteToFileDescriptorWithProgress
2	Foundation	____NSWriteDataToFileWithExtendedAttributes_block_invoke
3	Foundation	-[NSData(NSData) enumerateByteRangesUsingBlock:]
4	Foundation	__NSWriteDataToFileWithExtendedAttributes
5	InstabugCore	aes_decrypt_key
6	libdispatch.dylib	__dispatch_call_block_and_release
7	libdispatch.dylib	__dispatch_client_callout
8	libdispatch.dylib	__dispatch_queue_concurrent_drain
9	libdispatch.dylib	__dispatch_queue_invoke$VARIANT$mp
10	libdispatch.dylib	__dispatch_queue_override_invoke$VARIANT$mp
11	libdispatch.dylib	__dispatch_root_queue_drain
12	libdispatch.dylib	__dispatch_worker_thread3
13	libsystem_pthread.dylib	__pthread_wqthread
```

**Comment by Kmohamed** [comment] 2018-01-10 14:41
@keith  I am really interesting to know what `derive_key` means ?

**Comment by keith** [comment] 2018-01-10 14:45
Looks like that's a function in your framework:

```
% nm Pods/Instabug/InstabugCore.framework/InstabugCore | grep derive_key
00000000000778be T _derive_key
```

Looking at it in hopper it looks related to crypto, there's some hmac stuff going on, which lines up with the other part of that stack trace.

**Comment by Kmohamed** [comment] 2018-01-10 14:55
I think it may be like `__hidden` that appear in some stack traces but I try to debug the two issues but the crash is extremely hard without see the symbolicated method in InstabugCore.

**Comment by Kmohamed** [comment] 2018-01-10 15:00
I will investigate in the crash and get back to you soon.

**Comment by Kmohamed** [comment] 2018-01-11 09:44
@keith I found that this crash is related to ZipArchive which we use to convert files into .zip file and I just open an issue on Github https://github.com/ZipArchive/ZipArchive/issues/437 
I will keep you updated.

**Comment by Kmohamed** [comment] 2018-01-29 07:56
@keith This crash is fixed on version 7.8.2 could you please update to the latest.

**Closed by Kmohamed** 2018-01-29 07:56 UTC

**Comment by Kmohamed** [comment] 2018-01-29 08:02
@keith I would like to share some information about the crash. Actually this crash was caused by ZipArchive as you know but now we are using another framework to zip our files which is more stable in v7.8.2 
Thanks keith for your support.

**Comment by keith** [comment] 2018-01-29 19:53
Thanks, I'll keep  an eye out the next time we update. You might consider depending on ZipZap directly, instead of bundling it in your SDK. We actually already depend on it, so now we'll have 2 copies of this code. Luckily, since you prefixed the symbols, the only downside will be app size.
